spring:
  datasource:
    url: jdbc:mysql://localhost:3306/qc_dev
    username: qc_dev_user
    password: chollera
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false